import { TASK_STATUS } from './constants'

const now = new Date()
const today = now.toISOString()
const tomorrow = new Date(now.getTime() + 86400000).toISOString()
const nextWeek = new Date(now.getTime() + 5 * 86400000).toISOString()
const farFuture = new Date(now.getTime() + 18 * 86400000).toISOString()
const pastDate = new Date(now.getTime() - 3 * 86400000).toISOString()

export const mockUsers = [
  {
    id: 'matt',
    name: 'Matt',
    email: 'matt@example.com',
    pushToken: '',
    totalPoints: 14,
    weeklyPoints: 6,
  },
  {
    id: 'megan',
    name: 'Megan',
    email: 'megan@example.com',
    pushToken: '',
    totalPoints: 19,
    weeklyPoints: 8,
  },
]

export const mockTasks = [
  {
    id: '1',
    title: 'Call pediatrician',
    notes: 'Ask about Thursday follow-up slot.',
    assignedTo: 'matt',
    requestedBy: 'megan',
    dueDate: today,
    dueTime: '10:00 AM',
    urgency: 'Today',
    effort: 'Quick',
    category: 'Kids',
    clarity: 'Call completed and outcome noted',
    whyThisMatters: 'Keeps the appointment from slipping.',
    repeatType: 'none',
    repeatDays: [],
    status: TASK_STATUS.NOT_STARTED,
    createdAt: today,
    completedAt: null,
    snoozedUntil: null,
    isCompleted: false,
    isMissed: false,
    acknowledgedAt: null,
    lastActionAt: today,
    snoozeCount: 0,
    inProgress: false,
    startedAt: null,
    history: [{ type: 'created', at: today, by: 'megan' }],
  },
  {
    id: '2',
    title: 'Buy dog food',
    notes: 'Grab the salmon bag if they have it.',
    assignedTo: 'megan',
    requestedBy: 'matt',
    dueDate: tomorrow,
    dueTime: '',
    urgency: 'Due soon',
    effort: 'Medium',
    category: 'Home',
    clarity: 'Item purchased',
    whyThisMatters: 'We only have one scoop left.',
    repeatType: 'biweekly',
    repeatDays: [],
    status: TASK_STATUS.NOT_STARTED,
    createdAt: today,
    completedAt: null,
    snoozedUntil: null,
    isCompleted: false,
    isMissed: false,
    acknowledgedAt: today,
    lastActionAt: today,
    snoozeCount: 0,
    inProgress: false,
    startedAt: null,
    history: [{ type: 'created', at: today, by: 'matt' }],
  },
  {
    id: '3',
    title: 'Take out trash',
    notes: '',
    assignedTo: 'matt',
    requestedBy: 'matt',
    dueDate: nextWeek,
    dueTime: '',
    urgency: 'This week',
    effort: 'Quick',
    category: 'Home',
    clarity: 'Bins are out before pickup.',
    whyThisMatters: 'Avoids overflow.',
    repeatType: 'weekly',
    repeatDays: ['Tue'],
    status: TASK_STATUS.NOT_STARTED,
    createdAt: today,
    completedAt: null,
    snoozedUntil: null,
    isCompleted: false,
    isMissed: false,
    acknowledgedAt: today,
    lastActionAt: today,
    snoozeCount: 0,
    inProgress: false,
    startedAt: null,
    history: [{ type: 'created', at: today, by: 'matt' }],
  },
  {
    id: '4',
    title: 'Schedule dentist cleaning',
    notes: '',
    assignedTo: 'megan',
    requestedBy: 'megan',
    dueDate: farFuture,
    dueTime: '',
    urgency: 'Whenever',
    effort: 'Medium',
    category: 'Health',
    clarity: 'Appointment booked',
    whyThisMatters: 'Gets it on the calendar before summer slips.',
    repeatType: 'none',
    repeatDays: [],
    status: TASK_STATUS.NOT_STARTED,
    createdAt: today,
    completedAt: null,
    snoozedUntil: null,
    isCompleted: false,
    isMissed: false,
    acknowledgedAt: null,
    lastActionAt: today,
    snoozeCount: 0,
    inProgress: false,
    startedAt: null,
    history: [{ type: 'created', at: today, by: 'megan' }],
  },
  {
    id: '5',
    title: 'Send insurance payment',
    notes: '',
    assignedTo: 'matt',
    requestedBy: 'megan',
    dueDate: pastDate,
    dueTime: '',
    urgency: 'This week',
    effort: 'Quick',
    category: 'Money',
    clarity: 'Payment submitted and confirmed',
    whyThisMatters: 'Avoids a late fee.',
    repeatType: 'monthly',
    repeatDays: [],
    status: TASK_STATUS.NOT_STARTED,
    createdAt: pastDate,
    completedAt: null,
    snoozedUntil: null,
    isCompleted: false,
    isMissed: true,
    acknowledgedAt: null,
    lastActionAt: pastDate,
    snoozeCount: 2,
    inProgress: false,
    startedAt: null,
    history: [{ type: 'created', at: pastDate, by: 'megan' }],
  },
]
